### ISSUE TITLE
Undefined javascript symbols on Windows

### ISSUE THREAD

**Issue by dpage** [jonmmorgan/wxwebconnect#2]
Hi,

I'm in the process of moving my wxWebConnect project to use your fork of the code instead of the original as I need to be able to define custom protocol handlers. My Windows build is failing with:

webcontrol.obj : error LNK2001: unresolved external symbol __imp__JS_GetStringBytes
webcontrol.obj : error LNK2001: unresolved external symbol __imp__JS_ValueToString

If I revert the commit https://github.com/jonmmorgan/wxwebconnect/commit/71c17e81dcc232364e96553140a749f7fc4891da, then it builds and works perfectly. Any suggestions to fix this? I guess I could link with js3250.lib/dll, but that kinda defeats the point of the loose coupling with XULrunner.

Building on Windows XP Pro, VC++ Pro 2008, XULrunner SDK 1.9.2, wxWidgets 2.8.11.

Thanks!

**Comment by jonmmorgan** [comment]
Hi,

I link with js3250.dll when building.  I agree with you that it somewhat defeats the loose coupling, and would prefer a better way, but I wasn't able to find one when I did it.  I'm fairly certain you can't get at those symbols (or equivalent functionality) using the Gecko frozen functions that the rest of wxWebConnect uses.  It's possible you could get at the symbols using dlopen() or the Windows equivalent instead, but I haven't looked at it.

**Comment by dpage** [comment]
Thanks Jon. I'll see if I can get at them with function pointers.

**Comment by jonmmorgan** [comment]
Hi,

Thanks for prompting me: I was intending to look into this at some point, because linking to js3250.dll (or libmozjs.so on Linux) was a pain, but had dismissed it as too hard.  It turns out it's fairly easy to do once you set your mind to it.

I have made a first cut of doing this on Windows at https://github.com/jonmmorgan/wxwebconnect/commit/067dce9d870ef633d66b649d2bf100efe25728a9.  It works for me on Windows with linking to js3250.dll.  I will have to add the Linux and Mac version and clean it up a bit before it goes into the main repository, but hopefully it saves you a bit of time.

**Comment by dpage** [comment]
Oh cool - thanks. I was meaning to look at this today but my inbox has been getting the better of me so far. Once Windows works for me I'll be moving onto Linux/Mac as well so the corresponding fix there would also be most welcome.

**Comment by jonmmorgan** [comment]
Now working on Linux as well.  Mac is not yet tested, but probably works.

**Comment by dpage** [comment]
Seems like it should work on Mac - as far as I can tell, as I've yet to get it to actually display anything on that platform so haven't exhaustively tested anything there yet.

Thanks.
