### ISSUE TITLE
Mac OS X support - nothing rendered

### ISSUE THREAD

**Issue by dpage** [jonmmorgan/wxwebconnect#5]
Hi,

You mentioned Mac OS X support in a previous ticket. This is a platform I need to support, however I've so far been unsuccessful. If I copy the contents of /Library/Frameworks/XUL.framework/Versions/Current/ to the MacOS directory within the app bundle (required because of the paths specified in the various libraries, which are all relative to the executable location) I can successfully initialise, and apparently load web pages and images referenced on them (the event handlers fire, and I can see it loading the expected files); however, nothing is displayed, as if all rendering is disabled.

Have you tested on Mac yet? Any idea what might be causing this? I've stepped through the code, and as far as I can tell we're passing an appropriate handle from the wx app to gecko. The same code works fine on Linux and Windows.

Thanks.

**Comment by jonmmorgan** [comment]
I don't have a Mac and haven't tested Mac support, though I do know someone who has built and used it on a Mac using the code in this branch from a couple of months ago (and hopefully it hasn't been broken since then).  They were using wx 2.9 and wxCocoa, which my memory tells me was meant to work better than the old wxMac with Carbon because the XULRunner handles were Cocoa handles, rather than Carbon handles.

I have seen grey windows showing nothing on both Windows and Linux.  Usually it has meant that somewhere in the middle of the init engine method something has failed, and it has returned false from there and not completed [though I'm sure there could be other ways of it breaking on Mac].  How I have tended to debug it is by scattering large quantities of debug prints through the init engine method to see where it got up to, then through methods it calls, etc., then try to guess from there where and how it failed.  It has always worked eventually, but it's fairly primitive and annoying.

**Comment by dpage** [comment]
Ahh, Carbon vs. Cocoa could well explain it. I'm pretty sure it was working otherwise - I did step through the code much as you've described, and as I said, if I try to load a page from a website, it does so, including the images linked from the HTML of the page; I can see network traffic, and the relevant events fire as downloads start/stop.

Unfortunately this is an app with nearly 200K lines of code written for wx 2.8. I haven't tried 2.9 yet myself, but one of our other developers did some time back, and reckoned it was going to be a fair amount of work to update.

I'll try the demo app with 2.9 though, and report the results. Thanks!

**Comment by dpage** [comment]
I get the same result with 2.9.1 - the browser seems to download everything, but nothing is rendered. Will have to look further...

**Comment by jonmmorgan** [comment]
I would definitely start by making sure init engine has succeeded and all the necessary child libraries have been properly loaded.

**Comment by dpage** [comment]
It does init successfully, and load all the libraries without error. There is some output on stdout/stderr:

2010-12-22 13:46:21.536 testapp[31047:903] -[NSHIObject window]: unrecognized selector sent to instance 0xc2bc80
2010-12-22 13:46:21.538 testapp[31047:903] Mozilla has caught an Obj-C exception [NSInvalidArgumentException: -[NSHIObject window]: unrecognized selector sent to instance 0xc2bc80]

But I've yet to track down the source of that, and don't know if it's likely to be the cause of the problem or not anyway.
